---
- hosts: geoserver
  remote_user: ec2-user
  become: yes
  tasks:
    - name: get repo keys
      script: /opt/ansible/scripts/OpenGeo.sh
    - name: copy repo
      template: src=./Templates/OpenGeo.repo dest=/etc/yum.repos.d/OpenGeo.repo
    - name: install GeoServer
      yum: name=opengeo-server state=present
    - name: install GDAL
      script: /opt/ansible/scripts/gdal.sh
    - name: install gdal-mrsid
      yum: name=gdal-mrsid state=present
    - name: install jdbc
      script: /opt/ansible/scripts/jdbc.sh
    - name: mount the nfs
      script: /opt/ansible/scripts/mounts.sh
    - name: restart services
      service: name=tomcat state=restarted
    - name: config data directory
template:
      /usr/share/opengeo/geoserver/WEB-INF/web.xml

      -name: jdbc config template
      /var/lib/opengeo/geoserver/jdbcconfig/jdbcconfig.properties 
